# Generated by Django 5.2.17 on 2026-09-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='side',
            field=models.CharField(blank=True, choices=[('groom', 'Домод'), ('bride', 'Арӯс')], max_length=10),
        ),
    ]
