# Generated by Django 5.2.17 on 2026-09-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('groom_national', 'Либоси миллии домод (чапон, тоқӣ)'), ('groom_suit', 'Костюми домод'), ('bride_dress', 'Либоси арӯсӣ'), ('bride_national', 'Либоси миллии арӯс'), ('veil', 'Фатаи арӯс'), ('cosmetics', 'Косметика'), ('trousers', 'Шими домод'), ('furniture', 'Мебел (сеп)'), ('bedding', 'Кӯрпа ва кӯрпача'), ('jewelry', 'Заргарӣ')], max_length=20),
        ),
    ]
