# Generated by Django 5.2.17 on 2026-09-27 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='restaurants/videos/'),
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurants/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='myapp.restaurant')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
