# Generated by Django 5.2.17 on 2026-09-27 14:59

from django.db import migrations, models

# Sensible starting values for existing products; vendors/admins can change them later.
BY_CATEGORY = {
    'groom_suit': 'upper', 'groom_national': 'upper', 'trousers': 'lower',
    'bride_dress': 'full', 'bride_national': 'full',
}


def fill(apps, schema_editor):
    Product = apps.get_model('myapp', 'Product')
    for product in Product.objects.all():
        kind = BY_CATEGORY.get(product.category, 'none')
        if 'тоқӣ' in product.name.lower() or 'тоқи' in product.name.lower():
            kind = 'none'  # skullcaps are headwear
        product.tryon_category = kind
        product.save(update_fields=['tryon_category'])


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_restaurant_video_restaurantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tryon_category',
            field=models.CharField(choices=[('upper', 'Боло (куртка, чапон)'), ('lower', 'Поён (шим)'), ('full', 'Пурра (либоси дароз)'), ('none', 'Пӯшонда намешавад')], default='upper', max_length=10),
        ),
        migrations.RunPython(fill, migrations.RunPython.noop),
    ]
