# Generated by Django 5.2.17 on 2026-09-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_tryon_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='cars/3d/'),
        ),
    ]
