# Generated by Django 5.2.17 on 2026-09-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_car_model_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='interior',
            field=models.ImageField(blank=True, null=True, upload_to='cars/interior/'),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_credit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
