# Generated by Django 5.2.17 on 2026-09-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_car_interior'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='interior_depth',
            field=models.ImageField(blank=True, null=True, upload_to='cars/interior/'),
        ),
    ]
